### ISSUE TITLE
Protocol description

### ISSUE THREAD

**Issue by dudanov** [ivoh95/ESPHome-Haier#1]
Hi.
I want to rework the code and make it more readable.

There was a question about the protocol:

1. Do all messages have a 16-bit checksum that is added at the end of the message? When you receive a message from the air conditioner, you do not check this checksum. Is this done to simplify the code or is it not in the messages from the air conditioner?
2. WiFi messages are not understood. Do I need to send them, in what cases and how often?

Is it possible to quickly contact you, for example, in Telegram? Do you speak Russian?

Thanks in advance.

**Comment by ivoh95** [comment]
Hello, there has been some progress on this, and i get the feeling this repository will be depreciated soon.

 There is a much more complete version, the author wants to also support multiple haier protocols and support the native esp32 based board, as well as esp8266. The author decompiled the original firmware to solve most of the protocol. See links for details. 

https://github.com/paveldn/ESP32-S0WD-Haier

https://community.home-assistant.io/t/esp-haier-haier-air-conditioner-esp-home-wemos-d1-mini/127880/186
